"""init tables

Revision ID: 1738a3f8d0ea
Revises: 
Create Date: 2026-03-01 13:55:12.159423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1738a3f8d0ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('start_location', sa.String(length=255), nullable=False),
    sa.Column('start_street', sa.String(length=120), nullable=False),
    sa.Column('start_city', sa.String(length=80), nullable=False),
    sa.Column('start_state', sa.String(length=2), nullable=False),
    sa.Column('start_zip', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('distance_meters', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('miles', sa.Float(), nullable=False),
    sa.Column('drive_minutes', sa.Integer(), nullable=False),
    sa.Column('service_minutes', sa.Integer(), nullable=False),
    sa.Column('total_minutes', sa.Integer(), nullable=False),
    sa.Column('gallons', sa.Float(), nullable=False),
    sa.Column('gas_cost', sa.Float(), nullable=False),
    sa.Column('mpg', sa.Float(), nullable=False),
    sa.Column('gas_price', sa.Float(), nullable=False),
    sa.Column('buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.create_table('stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip', sa.String(length=5), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stops')
    op.drop_table('plan_metrics')
    op.drop_table('plans')
    # ### end Alembic commands ###
