"""add goal settings

Revision ID: 7105b2d8ec39
Revises: 1738a3f8d0ea
Create Date: 2026-03-07 13:45:36.006951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7105b2d8ec39'
down_revision = '1738a3f8d0ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_to_start', sa.Boolean(), nullable=False),
    sa.Column('buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('mpg', sa.Float(), nullable=False),
    sa.Column('gas_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal_settings')
    # ### end Alembic commands ###
